# docker-compose.yml
version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bidding_db
    ports:
      - "3306:3306"
  app:
    build: .
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: bidding_db
      JWT_SECRET: your_jwt_secret
    ports:
      - "3000:3000"
    depends_on:
      - db
